#!/usr/bin/env bash
# Copyright (c) 2025 thraciaexpelled on GitHub, All rights reserved

_omb_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "${_omb_root}/omb-cli/src/log.bash"

SRC_PATH=$(dirname "${BASH_SOURCE[0]}")
source "$SRC_PATH/backup.bash"
source "$SRC_PATH/run_command.bash"

function apply_chosen_theme {
    local old_func+=$CURRENT_FUNC
    CURRENT_FUNC="omb::theme::static.apply_chosen_theme"

    local theme_name=$1
    local theme_path="$HOME/.omb-themes.d/$theme_name.omb.bash"

    info "generating .omb-profile..."

    # TODO(Sun 02 Nov 2025 06:46:42 PM, fixbug): echo will not work with run_command
    echo -e "#\n## Generated by oh-my-bash in $(date)\n#\n\nexport OMB_CONFIG_SET=1\nsource $theme_path\n" | tee "$HOME/.omb-profile" > /dev/null

    # i'm very sorry for this
    if [[ $? == 0 ]]; then
        ok "generated .omb-profile in $HOME/.omb-profile"
    else
        error "cannot generate .omb-profile"
        exit 1
    fi

    if [[ -z $OMB_CONFIG_SET ]]; then
        info "appending to $HOME/.bashrc"
        echo -e "#\n## Generated by oh-my-bash in $(date)\n#\n\nsource $HOME/.omb-profile" >> $HOME/.bashrc
    fi

    ok "applied requested theme ($theme_name)"
    warn "to unset this theme, run 'oh-my-bash --theme --unset' OR restore your backup. DO NOT DO THIS YOURSELF."
}

function check_if_theme_exists {
    local old_func=$CURRENT_FUNC
    CURRENT_FUNC="omb::theme::static.check_if_theme_exists"

    local theme_name=$1
    for file in "$HOME"/.omb-themes.d/*; do
        if [[ $theme_name != "$(basename "$file" ".omb.bash")" ]]; then
            error "requested theme ($theme_name) not found"
            exit 1
        fi
    done

    CURRENT_FUNC=$old_func
}

function theme_set {
    local old_func+=$CURRENT_FUNC
    CURRENT_FUNC="omb::theme::theme_set"

    local theme_name=$1
    info "Searching for theme $theme_name in $HOME/.omb-themes.d"
    check_if_theme_exists "$theme_name"

    info "backing up before applying theme"
    start_backup

    info "applying requested theme ($theme_name)"
    apply_chosen_theme "$theme_name"

    CURRENT_FUNC=$old_func
}

function theme_unset {
    local old_func+=$CURRENT_FUNC
    CURRENT_FUNC="omb::theme::theme_unset"

    echo -e "#\n## Generated by oh-my-bash in $(date)\n#\n\nexport OMB_CONFIG_SET=1\n" | tee "$HOME/.omb-profile" > /dev/null

    # i'm very sorry for this
    if [[ $? != 0 ]]; then
        error "cannot unset current theme"
        exit 1
    fi

    ok "try running . $HOME/.bashrc"

    CURRENT_FUNC=$old_func
}

function theme_list {
    local old_func+=$CURRENT_FUNC
    CURRENT_FUNC="omb::theme::theme_list"

    printf "%s:\n" "$(bolden "Local themes")"

    local count=0
    for theme in "$HOME"/.omb-themes.d/*; do
        if [[ -e "$theme" ]]; then
            printf "    %d. %s\n" $count "$(color_fg "$(basename "$theme" ".omb.bash")" yellow)   "
            ((count++))
        fi
    done

    if [[ $count == 0 ]]; then
        warn "no themes installed locally"
    fi

    CURRENT_FUNC+=old_func
}